apps/precursor-chemicals/fields/index.js, apps/precursor-chemicals/index.js, apps/precursor-chemicals/sections/summary-data-sections.js, apps/precursor-chemicals/translations/src/en/fields.json, apps/precursor-chemicals/translations/src/en/pages.json, apps/precursor-chemicals/translations/src/en/validation.json
[CSL-31](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-31) - 1.10 PCA - 'Tell us about your main customers' (The organisation and how it operates)
Added screens for questions:
- Tell us about your main customers
- Tell us about your main suppliers
- What security measures do you have in place at the premises?
- Describe how you secure your premises
Steps have been split into relevant sections and commented out to shorten the user journey to the summary page and speed up the testing process.
=> CSL-31: PCA - Tell us about your main customers

apps/precursor-chemicals/behaviours/custom-validation.js, apps/precursor-chemicals/fields/index.js, apps/precursor-chemicals/index.js, apps/precursor-chemicals/sections/summary-data-sections.js, apps/precursor-chemicals/translations/src/en/fields.json, apps/precursor-chemicals/translations/src/en/pages.json, apps/precursor-chemicals/translations/src/en/validation.json, apps/precursor-chemicals/views/content/en/received-criminal-conviction-instructions.md, apps/precursor-chemicals/views/criminal-convictions.html, apps/precursor-chemicals/views/partials/warning-received-criminal-conviction.html
- [CSL-28](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-28) - PCA - Has anyone employed by your company ever received criminal convictions? (about the applicants)
- Creating new pages for precursor chemicals new applications.  Added received criminal convictions, Invoicing address and contact details
=> CSL 28- PCA - Added new pages received criminal convictions, Invoicing address and contact details

apps/precursor-chemicals/index.js
Restore all form steps that have been commented out previously to reduce the scope of the user journey to `About the applicants` section
=> Reinstate all steps

apps/precursor-chemicals/behaviours/custom-validation.js, apps/precursor-chemicals/fields/index.js, apps/precursor-chemicals/index.js, apps/precursor-chemicals/sections/summary-data-sections.js, apps/precursor-chemicals/translations/src/en/fields.json, apps/precursor-chemicals/translations/src/en/pages.json, apps/precursor-chemicals/translations/src/en/validation.json
- [CSL-27](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-27) - PCA - Which email address should the licence be sent to (Finalise application)
- Creating new pages for precursor chemicals new applications.  Added new pages for licence email and who is completing application details
=> CSL-27 - PCA - Added new pages licence email and who is completing in new application flow

apps/precursor-chemicals/sections/summary-data-sections.js
This PR refactors the code to standardise the creation of arrays using a uniform format. The changes improve readability and maintainability by using a consistent approach for array creation and joining elements with newline characters.
=> Refactor array creation for consistency

apps/precursor-chemicals/fields/index.js, apps/precursor-chemicals/index.js, apps/precursor-chemicals/sections/summary-data-sections.js, apps/precursor-chemicals/translations/src/en/fields.json, apps/precursor-chemicals/translations/src/en/pages.json, apps/precursor-chemicals/translations/src/en/validation.json, apps/precursor-chemicals/views/extra-application-information.html
Relates [CSL-15](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-15)
Add pages for regulatory affairs and extra information for finalise application section for Precursor Chemicals
=> CSL-15-PCA-reg-affairs

apps/precursor-chemicals/index.js, apps/precursor-chemicals/sections/summary-data-sections.js, apps/precursor-chemicals/translations/src/en/fields.json, apps/precursor-chemicals/translations/src/en/pages.json, apps/precursor-chemicals/translations/src/en/validation.json, apps/precursor-chemicals/views/content/en/conduct-certificate-file-requirements.md, apps/precursor-chemicals/views/upload-company-certificate.html, apps/precursor-chemicals/views/upload-conduct-certificate.html
[CSL-23](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-23) Adds the configuration and files required to display the "Upload a certificate of good conduct" page
=> CSL-23 - Upload a certificate of good conduct (Evidence)

.devcontainer/Dockerfile, .drone.yml, Dockerfile, bin/sanity_check_build.sh
Renaming our default branches from main to master until a team decision is made to stop doing so. This task involves renaming the default branch of our GitHub repository, and update the deployment script to align with this directive.
- removed redundant packages from Docker file, and update all installed packages instead
- updated sanity check script to replace hardcoded default branch
- updated drone yaml file to replace hardcoded default branch ref with alias
=> CSL-122: Rename default branch

apps/common/behaviours/custom-validation.js, apps/controlled-drugs/translations/src/en/validation.json, apps/precursor-chemicals/translations/src/en/validation.json
[CSL-53](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-53) - updated the validation regex for company number. It can be either 8 digits or 2 letters followed by 6 digits
Followed the validation rules from controlled drugs form figma.
=> CSL - 53 - Updated the company number validation regex

apps/controlled-drugs/behaviours/custom-redirect.js, apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json
[CSL-84](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-84) and [CSL-85](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-85)  -  Added pages for person responsible for witnessing the destruction of durgs details, DBS information and DBS details.
- Updates to summary sections and custom redirection added as per the PR #60 
Commits from previous branches as this one began before merge of previous to master
=> CSL - 84, 85 - CD - Added responsible for witnessing the destruction of drugs pages

apps/controlled-drugs/behaviours/custom-redirect.js, apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json
Adds the section around providing a service under contract to the controlled drugs form
Pages /service-under-contract, /service-details, /service-expiry-date, /status-of-site
'status-of-site is not exactly part of the section, but is added to the ticket per the way the design looks'
Added custom-redirects for summary due to conditional logic.
[CSL-96](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-96)
=> CSL-96: 1.20 CD - Are you providing a service under a contract

apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json
[CSL-101](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-101) -  Added pages for Security features, /separate-room and /safe-or-cabinet 
=> CSL-101 - CD - Added security features pages in CD flow

apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json
[CSL-104](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-104) -  Added pages for /storage-details, /electronic-alarm-system and /alarm-system-details
=> CSL0104 - CD- Added electronic alarm system details pages

apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json
Relates [CSL-105](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-105)
- Added fork condition to `/safe-or-cabinet` step
=> CSL-105[CD]-separate-zone

apps/common/behaviours/custom-validation.js, apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json
Adds detail for steps, fields, validations and summary sections related to pages referenced in [CSL-108](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-108)
=> CSL-108: 1.31 - CD - Which email address should we send the licence to?

apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json, apps/controlled-drugs/views/application-submitted.html, apps/controlled-drugs/views/content/en/cd-application-submitted.md, apps/controlled-drugs/views/content/en/declaration.md, apps/controlled-drugs/views/declaration.html, assets/scss/app.scss
[CSL-110](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-110) - Declaration and Application submitted page in controlled drugs flow
=> CSL-110 - CD - Added declaration and application submitted page

apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/buttons.json, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json, apps/controlled-drugs/views/company-registration-certificate-name-change.html, apps/controlled-drugs/views/register-again.html
[CSL-113](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-113) , [CSL-114](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-114)-  Added pages for /company-number-changed, /company-name-changed, /register-again, /company-registration-certificate-name-change
=> CSL - 113, 114 - CD - companies House reference number, name , upload company certificate

apps/controlled-drugs/fields/index.js, apps/controlled-drugs/index.js, apps/controlled-drugs/sections/summary-data-sections.js, apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/pages.json, apps/controlled-drugs/translations/src/en/validation.json
Relates [CSL-117](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-117)
*change to validation messages/logic for controlled drugs date moving site field to match precursor chemicals
=> CSL-117: CD - contract-start

apps/common/index.js, apps/common/translations/src/en/buttons.json, apps/common/translations/src/en/fields.json, apps/common/translations/src/en/pages.json, apps/common/views/content/en/before-you-start.md, apps/common/views/content/en/not-registered-yet.md, apps/common/views/content/en/use-this-service.md, apps/common/views/sign-in.html, apps/common/views/start.html
*adds start pages to CSL form 
relates [CSL-125](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-125)
=> CSL-125-add-start-pages

apps/controlled-drugs/translations/src/en/fields.json, apps/controlled-drugs/translations/src/en/validation.json, apps/industrial-hemp/translations/src/en/validation.json, apps/precursor-chemicals/translations/src/en/fields.json, apps/precursor-chemicals/translations/src/en/validation.json
Changes error messages on PCA, CD and THC flows
Relates [CSL-231](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-231)
=> CSL-231-change-error-messages

apps/industrial-hemp/behaviours/custom-redirect.js, apps/industrial-hemp/fields/index.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/fields.json, apps/industrial-hemp/translations/src/en/pages.json, apps/industrial-hemp/translations/src/en/validation.json, apps/industrial-hemp/views/register-again.html
[CSL](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-149) - Has your Companies House reference number changed since your last application
According to figma design
=> CSL 149 - THC - Companies House reference number

apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/fields.json, apps/industrial-hemp/translations/src/en/pages.json, apps/industrial-hemp/translations/src/en/validation.json, apps/industrial-hemp/views/company-registration-certificate.html, apps/industrial-hemp/views/content/en/company-certificate-file-requirements.md
[CSL-150](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-150) - Upload company registration certificate as evidence of name change
According to figma design
Tested Manually
=> CSL 150 Upload company registration certificate

apps/industrial-hemp/index.js
CSL-149 Bug fix 
When users tries to change an answer on the summary page , it start a new journey
Add confirm step in the index file
=> Bugfix CSL 149

apps/industrial-hemp/fields/index.js, apps/industrial-hemp/translations/src/en/pages.json, apps/industrial-hemp/translations/src/en/validation.json
- Added missing error messages for CSL-151 
-Added date constraint for CSL-141
=> Bugfix CSL-144 and CSL-151

apps/industrial-hemp/fields/index.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/fields.json, apps/industrial-hemp/translations/src/en/pages.json, apps/industrial-hemp/translations/src/en/validation.json
[CSL-183](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-183),  [CSL-184](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-184) -  Added pages for /seed-supplier-details, /customer-base-details, /end-product-details, /end-product-production, /seed-type-details, /thc-content-level in THC form flow
=> CSL-183, CSL- 184 - THC - Added 6 pages in THC flow

apps/industrial-hemp/fields/index.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/fields.json, apps/industrial-hemp/translations/src/en/pages.json, apps/industrial-hemp/translations/src/en/validation.json, apps/industrial-hemp/views/content/en/perimeter-details.md, apps/industrial-hemp/views/content/en/perimeter-requirement.md, apps/industrial-hemp/views/perimeter-details.html, apps/industrial-hemp/views/perimeter-images.html, config.js
[CSL-181](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-181) - 1.21 LTHCC- Perimeter Details
[Perimeter details](https://www.figma.com/design/WNady81HOqgtqgI3L5kAia/CSL---Low-THC-Cannabis?node-id=1-24619&t=YCetZ0bdD17R9I6T-4)
[Upload images of the perimeter](https://www.figma.com/design/WNady81HOqgtqgI3L5kAia/CSL---Low-THC-Cannabis?node-id=1-18433&t=YCetZ0bdD17R9I6T-4)
- added uploaded file to summary page
=> CSL 181 1.21 LTHCC- Perimeter Details

apps/common/behaviours/custom-validation.js, apps/industrial-hemp/behaviours/other-business-detail.js, apps/industrial-hemp/fields/index.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/buttons.json, apps/industrial-hemp/translations/src/en/fields.json, apps/industrial-hemp/translations/src/en/pages.json, apps/industrial-hemp/translations/src/en/validation.json, apps/industrial-hemp/views/content/en/cultivation-details.md, apps/industrial-hemp/views/content/en/other-businesses.md, apps/industrial-hemp/views/other-businesses-details.html, apps/industrial-hemp/views/other-businesses-summary.html, config.js
[CSL-178](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-178) - 1.18 LTHCC-Are there any other businesses operating from your intended cultivation site?
[CSL-179](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-179) - 1.19 LTHCC- Businesses adjacent to or operating from your cultivating site
According to Figma design 
[Figma design for CSL-178](https://www.figma.com/design/WNady81HOqgtqgI3L5kAia/CSL---Low-THC-Cannabis?node-id=1-25073&t=FpvimqQNebPIDuLf-4_)
[Figma design for CSL-179](https://www.figma.com/design/WNady81HOqgtqgI3L5kAia/CSL---Low-THC-Cannabis?node-id=1-25073&t=FpvimqQNebPIDuLf-4_)
- Added Field on each page
- Added validation control on each fields
- added summary page for aggregated values
- display the values n the summary page
=> CSL- 178 and 179

apps/industrial-hemp/fields/index.js, apps/industrial-hemp/translations/src/en/validation.json
Minor bug fix for error message
=> CSL-178 Bug fix

apps/controlled-drugs/views/application-submitted.html, apps/controlled-drugs/views/content/en/cd-application-submitted.md, apps/industrial-hemp/fields/index.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/fields.json, apps/industrial-hemp/translations/src/en/pages.json, apps/industrial-hemp/translations/src/en/validation.json, apps/industrial-hemp/views/application-submitted.html, apps/industrial-hemp/views/content/en/declaration.md, apps/industrial-hemp/views/content/en/thc-application-submitted.md, apps/industrial-hemp/views/declaration.html, apps/precursor-chemicals/views/application-submitted.html, apps/precursor-chemicals/views/content/en/pca-application-submitted.md, apps/registration/views/company-type.html, apps/views/company-type.html
[CSL-200](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-200) -   Added /declaration, /application-submitted pages in THC form flow 
=> CSL - 200 - THC - Added declaration and application submitted pages

apps/common/behaviours/set-feedback-url.js, apps/common/index.js, apps/controlled-drugs/index.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/pages.json, apps/precursor-chemicals/index.js, apps/registration/index.js, config.js
[CSL-128](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-128) -  CSL applications - feedback
Feedback links to be provided on each application form page.
=> CSL 128 application feedback

apps/common/behaviours/submit-request.js, apps/industrial-hemp/behaviours/custom-redirect.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/buttons.json, apps/industrial-hemp/translations/src/en/pages.json
[CSL-213](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-213) -Low THCC - Information you have given us (save and return / save and exit functionality)
Adds behaviours to implement save and continue/exit forLow THC applications and to view and change saved progress in the 'Information you have given us' page.
- Update Low THC custom-redirect to work with 'Information you have given us' change links and return redirections
- Add behaviours from common to enable new functionalities
=> CSL - 213 - THC - Added Information you given us page and save and exit feature

apps/common/behaviours/submit-request.js, apps/registration/behaviours/submit-request.js
Added `licenceType` variable for Application confirmation email template;
Added mocked value for `referenceNumber` variable;
Relates to [CSL-263](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-263)
=> CLS-263: Added licenseType into personalisation; mock value for referenceNumber;

apps/common/index.js, apps/common/translations/src/en/pages.json, apps/common/views/content/en/accessibility.md, apps/common/views/static/accessibility.html
[CSL-261](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-261) - CSL - Accessibility Statement
To display accessibility statement
- Added template for accessibility in common folder of view section to enable render a. customised accessibility page
- Added markdown page
- Added css styling to accessibility .html page
=> CSL-261 Accessibility statement

config.js, jest.config.json, package.json, test/unit/pass-generator.test.js, utils/pass-generator.js, yarn.lock
[CSL-247](http://collaboration.homeoffice.gov.uk/jira/browse/CSL-247) - Password generation
According to Figma
- Added crypto-random-string to node module
- Added unit test
- Unit test 
-
=> CSL-247 Password generation

apps/common/behaviours/submit-request.js, apps/controlled-drugs/views/content/en/cd-application-submitted.md, apps/industrial-hemp/views/content/en/thc-application-submitted.md, apps/precursor-chemicals/views/content/en/pca-application-submitted.md, apps/registration/behaviours/submit-request.js, apps/registration/views/content/en/reg-application-submitted.md
Adds reference number placeholder to views for submission pages on each of journeys
Relates [CSL-228](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-228)
=> CSL-228-add ref number placeholder to views for flows

apps/industrial-hemp/fields/index.js, apps/industrial-hemp/index.js, apps/industrial-hemp/sections/summary-data-sections.js, apps/industrial-hemp/translations/src/en/fields.json, apps/industrial-hemp/translations/src/en/validation.json, apps/precursor-chemicals/sections/summary-data-sections.js, apps/precursor-chemicals/translations/src/en/pages.json
Relates [CSL-302](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-302)
* update summary page invoicing details so they are consistent with CD/Low thc flows
=> CSL-302-update-summary-page-invoicing-details

apps/common/views/content/en/not-registered-yet.md
[CSL-306](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-306) -  change to sign-in page wording
[CSL-307](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-307)
[CSL-308](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-308)
=> CSL 306 307 308

utils/icasework/build-case-data.js
[CSL 305](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-305) - CD: Same role details / site details not being copied into iCasework
=> Bug Fix CSL 305
