- .drone.yml
Makes scheduled `security_scans` pipeline job fail in the case of vulnerabilities found in node package or OS scans
As with HOF ways of working for vulnerabilities, these scheduled scans should fail to alert us of security issues in this project. They should also trigger a slack alert in the relevant HOF slack channel.
Updated `FAIL_ON_DETECTION` bool for scan jobs `cron_trivy_scan_node_packages` and `cron_trivy_scan_image_os` in `.drone.yml`
This can be tested by temporarily increasing the cron schedule and checking if we receive all required notification.
> CSL-20 Ensure failure of cron security_scans pipeline for failing node/os scan steps

- .drone.yml
Made the trigger condition for slack hook steps based on failure status in cron pipelines a list instead of a plain key/value value.
The previous config did not trigger the slack hook step when the pipeline had failed on a previous step. this update alters it to match other working pipeline steps in other projects and [drone's documentation on triggers](https://docs.drone.io/pipeline/kubernetes/syntax/trigger/#by-status).
> CSL-20: Make trigger conditions for slack pipeline steps a list

- .drone.yml
- bin/clean_up.sh
Update dependencies of `security_scans` steps in the pipeline so that the slack notification step will successfully run if failure is detected in the vulnerability scan steps.
The slack hook step was not running before as it was not detecting failures or was skipping before.
> CSL-44 Update cron step dependencies to ensure slack step runs in scan failure cases

- apps/precursor-chemicals/fields/index.js
- apps/precursor-chemicals/index.js
- apps/precursor-chemicals/sections/summary-data-sections.js
- apps/precursor-chemicals/translations/src/en/fields.json
- apps/precursor-chemicals/translations/src/en/pages.json
- apps/precursor-chemicals/translations/src/en/validation.json
Relates [CSL-64](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-64)
Added why chemicals are needed step to Precursor Chemicals
> CSL-64-add-why-chemicals-are-needed-page

- apps/precursor-chemicals/fields/index.js
- apps/precursor-chemicals/index.js
- apps/precursor-chemicals/translations/src/en/fields.json
- apps/precursor-chemicals/translations/src/en/pages.json
- apps/precursor-chemicals/translations/src/en/validation.json
- apps/precursor-chemicals/views/application-submitted.html
- apps/precursor-chemicals/views/content/en/pca-application-submitted.md
- apps/precursor-chemicals/views/declaration.html
- assets/js/index.js
- assets/scss/app.scss
- [CSL-29](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-29) - PCA - Declaration & Precursor Chemicals Application submitted pages
- Creating new pages for precursor chemicals new applications. Added Declaration & Precursor Chemicals Application submitted pages
> CSL - 29 - PCA - Added declaration and application submitted page 

- .devcontainer/devcontainer.env.sample
- .devcontainer/docker-compose.dev.yml
- apps/common/behaviours/remove-document.js
- apps/common/behaviours/save-document.js
- apps/precursor-chemicals/index.js
- apps/precursor-chemicals/sections/summary-data-sections.js
- apps/precursor-chemicals/translations/src/en/buttons.json
- apps/precursor-chemicals/translations/src/en/fields.json
- apps/precursor-chemicals/translations/src/en/journey.json
- apps/precursor-chemicals/translations/src/en/pages.json
- apps/precursor-chemicals/translations/src/en/validation.json
- apps/precursor-chemicals/views/content/en/file-requirements.md
- apps/precursor-chemicals/views/upload-company-certificate.html
- assets/js/index.js
- assets/scss/_file-upload.scss
- assets/scss/app.scss
- bin/deploy.sh
- config.js
- kube/app/deployment.yml
- kube/file-vault/file-vault-deployment.yml
- package.json
- server.js
- utils/file-upload.js
- utils/index.js
- yarn.lock
[CSL-24](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-24) Adds the configuration and files required to display the "Upload company registration certificate" page and enable uploads via file-vault to S3.
The updates will allow deployment of a file-vault container in the namespace that can connect to the S3 bucket, and add the page and functionality for uploads
> CSL-24: Company Registration Certificate upload

- apps/precursor-chemicals/index.js
- apps/precursor-chemicals/translations/src/en/validation.json
- apps/precursor-chemicals/views/upload-company-certificate.html
- apps/precursor-chemicals/views/upload-conduct-certificate.html
rename fields for file-upload in translations
so that it can be reused and to avoid confusion caused by references to non-existent fields.
> CSL-23: rename field for file upload

- bin/deploy.sh
Make file-vault deployments happen before app deployments Make file-vault ingresses run before file-vault deployments
Updated the order of processing kube resources by `kd` in `bin/deploy.sh`
- We wanted file-vault files to run before app files so that the pipeline will fail earlier that some config is failing before the app fully deploys.
- File-vault deployments are failing as the deployment resource tries to create the `file-vault-cert` as a volume before it is generated (or updated) by deploying first time changes to the `file-vault-ingress`. UAT builds will fail until resources are created in a useful order
> Update deploy.sh to fix file-vault certificate

- bin/deploy.sh
Corrected filenames for Kubernetes resources deployed in `deploy.sh`
These were added incorrectly in the previous commits
> Correct filenames deployed in deploy.sh for file-vault

- .drone.yml
Updated deployment file to specify the production url `www.licensing-for-controlled-substances.homeoffice.gov.uk`
> Udate Production url

- apps/precursor-chemicals/data/chemicals.json
As a part of [CSL-26](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-26) - 1.6 PCA - Which category is the new substance? (About the licence)
This PR adds a new JSON file named `chemicals.json` that contains a list of chemicals. Each chemical entry includes the following fields:
- `label`: The name of the chemical along with its CN code.
- `value`: The name of the chemical.
- `category`: The category of the chemical.
- `cnCode`: The CN code of the chemical.
This file will be used to manage and reference chemicals within the application.
Source of the latest the chemicals list: https://www.gov.uk/guidance/precursor-chemical-licensing#categories
> CSL-26: PCA - Add list of chemicals

- apps/precursor-chemicals/behaviours/filter-chemicals.js
- apps/precursor-chemicals/fields/index.js
- apps/precursor-chemicals/index.js
- apps/precursor-chemicals/translations/src/en/fields.json
- apps/precursor-chemicals/translations/src/en/pages.json
- apps/precursor-chemicals/translations/src/en/validation.json
- assets/js/index.js
- assets/scss/_autocomplete.scss
- assets/scss/app.scss
- package.json
- test/unit/filter-chemicals.test.js
- yarn.lock
Adding 'Which category is the substance?' and ''Which chemical are you applying for?' pages with filtering of available chemicals to select in 'which chemical' depending on 'which category' was chosen.
This is for Precursor chemicals 'About the licence' section.
[CSL-26](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-26)
Unit tests added
As these two pages will eventually be part of an aggregate loop with intermediate summary page it is expected that additional logic will be added to clear values and manage routing for these fields in subsequent tickets.
> CSL-26: Which category / which chemical (PC - About licence)

- apps/precursor-chemicals/behaviours/filter-chemicals.js
- apps/precursor-chemicals/fields/index.js
- apps/precursor-chemicals/index.js
- apps/precursor-chemicals/translations/src/en/fields.json
- apps/precursor-chemicals/translations/src/en/pages.json
- apps/precursor-chemicals/translations/src/en/validation.json
[CSL-82](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-82) Adds the configuration and files required to display the "which operation and what operation" pages
The looping behavior and summary page logic are not included in this ticket and will be addressed in CSL-25.
This ticket change includes,
- The title on the two pages will dynamically update based on the selected chemical.
- Implement necessary validations for the two pages.
> CSL-82 - PCA- Which operation applies to this licence for 'X' (About the licence)

- apps/precursor-chemicals/data/chemicals.json
- apps/precursor-chemicals/fields/index.js
- apps/precursor-chemicals/translations/src/en/validation.json
Updated  chemicals list to replace `*` with `(Northern Ireland only)` for user reference
Some chemicals are only applicable to Northern Ireland, but there is no validation to prevent users from selecting such chemicals if they are registered elsewhere.
- Updated maxlength validation for 'what-operation' field
> CSL-26: PCA updated chemicals list

- apps/precursor-chemicals/fields/index.js
- apps/precursor-chemicals/translations/src/en/validation.json
[CSL-194](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-194) -  A change request to update and synchronise the validation rules for the full name and DBS reference fields across both PCA and CD forms
- Added additional validation for min and max length on these fields
- updated the error message in validation.json
> CSL-194 - PCA - Validation update on full name and DBS reference

- apps/controlled-drugs/index.js
Add a fork from the end of 'status-of-site' page dependent on the radio option selected in that form
This was missed in the main PR and raised by QAT
> CSL-96: amend forking from step 'status-of-site'

- bin/deploy.sh
- kube/hof-rds-api/ingress.yml
* Internal Ingress to be deployed and configured as part of CI/CD
* Internal ingress annotations are added to hof-services-config
* Certs are added to the namespaces manually needs to be automated
* Internal ingress is required in order to rotate and replace certs 
* We are using Common Names/ FQDN in Secrets and certs. 
* Hence decided to deploy Internal Ingress to avoid issues
* Add the internal ingress for data service and ensure we deploy it via CI/CD ( automated) 
* Ensure the certs and secrets are using the same Common name/ FQDN aligning to the ingress urls used
* We will need to test the annotations configured to the ingress during drone build
> CSL-139: Add internal ingress to dataservice deployment

- apps/controlled-drugs/index.js
[CSL-202](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-202)
TICKET TO REFLECT AMENDMENT TO PAGE DESIGN - Do you require somebody within your company to be authorised to witness the destruction of controlled drugs & Who is responsible for witnessing the destruction of controlled drugs
to cover scenarios where user should be redirected to '/company-registration-certificate' step, unless user is an Existing licensee renewing or changing a currently licensed site.
User will be redirected to `/company-registration-certificate` step, if on step`/witness-destruction-of-drugs` answer is 'No' or if on step `/who-witnesses-destruction-of-drugs` answer is 'The same'
> CSL-202: forking logic to skip /company-registration-certificate step

- apps/controlled-drugs/behaviours/custom-redirect.js
- apps/controlled-drugs/index.js
- apps/precursor-chemicals/behaviours/custom-redirect.js
- apps/precursor-chemicals/index.js
Added custom redirect from /company-number-changed to /register-again and removed classic HOF forking as a result of issues reported in comments in [CSL-113](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-113)
Added `SetSummaryReferrer` and `CustomRedirect` behaviours as there is derivation from the 'edit' action.
When changing the yes/no answer in /company-number-changed **after** reaching the summary and receiving the /register-again page as a result HOF was losing several steps and values from the session, causing the user to have to fill the form again from near the start and eventually errors in resolving summary data sections.
It was unclear exactly what was causing this - possibly as a result of reaching the end of a fork journey, or possibly due to not being able to …
> CSL-113: Add custom redirect around /register-again step

- kube/html-pdf/html-pdf-deployment.yml
* Using html-pdf-converter image with Node v 22 and upgraded node packages
* Fixed vulnerabilities in the image
* Testing in Branch env
* https://collaboration.homeoffice.gov.uk/jira/browse/CSL-201
* Large number of Critical and High CVE Vulnerabilities have been detected by Trivy Scan
* Node image v18 is outdated. HOF is moving to v20 and v22 in future Goals.
* Replace html-pdf-converter image with latest
* Add a comment to explain the version and Date.
* Regression testing in Branch and then merge to master to deploy and test in UAT, Stage and promote to Prod
* Check boxes will ticked as we pass through each env
* Drone build is successful
* Pods are Healthy
* Staging environment has been commented out in pipeline 4 years ago by team
here is an [example …
> CSL-201: Update html-pdf-converter image to latest v3.0.0

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
Added the license holder details and license holder address pages for your low THC journey See ticket [CSL-145](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-145)
As per business requirement
- Added the license-holder-details and licence-holder-address fields in the fields/index.js
- Added the routes for the two pages
- Added the relevant validation messages
Manual developer test for the html pages.
> [CSL 145 THC] Add License Holder details pages

- apps/common/behaviours/custom-validation.js
- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
Added details of the person for the site page. 
As per business requirements
Added name, email, uk phone and DBS checkbox fields for the added details of the person for the site page
Manual developer test conducted
> [CSL-159-THC] add details page for person responsible for the site

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
- apps/industrial-hemp/views/content/en/dbs-updates-warning.md
- apps/industrial-hemp/views/partials/warning-dbs-subscription-responsible-officer.html
- apps/industrial-hemp/views/site-responsible-officer-dbs-updates.html
Added two pages for the section of  DBS information for the person responsible for the site. See ticket [CSL-158](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-158)
As per business requirements
- Added the new fields for the DBS information section
- Added the validations and routes to reach the new pages
- Updated the summary-data-section.js file to include the new field data in the summary page
- Added a Markdown file which contains the warning component for the DBS updates page
Manual developer test conducted
> [CSL-158-THC] add DBS information for person responsible pages

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
Added two new pages for the witness of destruction of the plant section. Please see ticket [CSL-164](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-164). Also updated the summary label for the responsible-officer-dbs-subscription. This is for the following ticket [CSL-158](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-158)
As per business requirements
- Added new fields for the destruction of plant section
- Added the new routes for these two pages
- Updated the summary page content to take into account these new fields
- Added a fork for the /how-leaves-flowers-destroyed page based on the answer chosen in /witness-destruction-plant plant
- Updated the summary label for the responsible-officer-dbs-subscription field
Manual developer test conducted
> [CSL 164 THC] add new pages for authorised witness destruction of the plant

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
- apps/industrial-hemp/views/authorised-witness-dbs-updates.html
- apps/industrial-hemp/views/content/en/received-criminal-conviction-instructions.md
- apps/industrial-hemp/views/criminal-conviction.html
- apps/industrial-hemp/views/partials/warning-received-criminal-conviction.html
- apps/industrial-hemp/views/site-responsible-officer-dbs-updates.html
[CSL-167](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-167) -  Added pages for /legal-business-proceedings, /legal-business-proceeding-details, and /criminal-conviction
> CSL - 167 - THC - Added legal proceedings and criminal conviction pages in LTHCC

- apps/registration/fields/index.js
- apps/registration/index.js
- apps/registration/sections/summary-data-sections.js
- apps/registration/translations/src/en/fields.json
- apps/registration/translations/src/en/journey.json
- apps/registration/translations/src/en/pages.json
- apps/registration/translations/src/en/validation.json
Adds licence details and licence address pages to registration journey
[CSL-129](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-129)
> CSL- REG -129-licence-details

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
[CSL-168](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-168),  [CSL-169](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-169)-  Added pages for /other-regulatory-licences, /other-licence-details, /licence-refused and /refusal-reason
Validation error messages are updated.
> CSL - THC - 168, 169 - Added pages for other regulatory licences and refused licences 

- apps/registration/fields/index.js
- apps/registration/index.js
- apps/registration/sections/summary-data-sections.js
- apps/registration/translations/src/en/fields.json
- apps/registration/translations/src/en/pages.json
- apps/registration/translations/src/en/validation.json
Added two pages "Is the business a registered charity" and "Has your legal identity changed at Companies House in the last 3 years?" pages. Please see ticket [CSL-136](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-136)
As per business requirements
- Added two new fields for the two pages in the field/index.js file
- Added the routes for the two pages in the index.js file
- Updated the confirm page to include the two new fields
- Added the relevant text for the fields and validation json files
- Added a fork for correct redirection on the "Has your legal identity changed at Companies House in the last 3 years?" page. 
Manual developer test conducted
Else? (optional)
> [CSL 136 Registration] add business charity section pages

- apps/industrial-hemp/sections/summary-data-sections.js
To fix the issue in UAT, added the conditional check in summary page field to hide when selecting the option 'no' in page /other-regulatory-licences
> CSL-168 - Updated the summary page field conditional check 

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
[CSL-144](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-144) - 3.1 LTHCC-When does the contract start.
According to figma design 
- Fix bug for CSL 151 to display field in the summary page
- Added fields and routes to each page according to figma designs
- Added validation control for each pages
- display necessary field to summary page
Tested locally
> CSL 144 When the contract start

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
- apps/industrial-hemp/views/content/en/apply-for-controlled-drugs-licence.md
- apps/industrial-hemp/views/no-licence-needed.html
- apps/registration/fields/index.js
- apps/registration/translations/src/en/validation.json
- assets/scss/app.scss
[CSL-171](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-171) , [CSL-172](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-172), [CSL-199](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-199)-  Added pages for /company-type, /company-certificate, /business-model, /cultivate-industrial-hemp in THC form flow
updated the validation minlength and maxlength for name of reponsible person field in /licence-holder-details page in registration flow
> CSL - THC - 171, 172 - Added pages in THC flow

- apps/controlled-drugs/fields/index.js
- apps/controlled-drugs/translations/src/en/validation.json
- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
- apps/precursor-chemicals/fields/index.js
- apps/precursor-chemicals/translations/src/en/validation.json
[CSL-233](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-233), [CSL-234](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-234) - validation amendment in contract start date field
Date validation on this page needs to be made consistent with Low THC form [CSL-144](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-144)
Added summary label for where-cultivating-cannabis field in pages.json. changes related to ticket  - [CSL-173](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-173)
> CSL-233, 234 - contract start date validation 

- apps/industrial-hemp/translations/src/en/validation.json
swapped the validation error message between before and after in Low THC cannabis flow.
Bug fix in [CSL-144](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-144)
> CSL - 144 - THC - updated the validation error message

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/journey.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
[CSL-188](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-188) -   Added /invoicing-address, /invoicing-contact-details, /licence-email-address pages in THC form flow 
> CSL-188 - THC - Added invoicing address and contact details and licence email address pages

- apps/views/session-timeout.html
[CSL-127](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-127)
Adds the service name / title to the black header bar in session-timeout.html
This information was not previously displayed in the template. As an error based template it does not inherit those values from page.html as normal pages do. This PR adds the dynamic header values for session-timeout.html which enables the heading.
> CSL-127 Add service name to headers on session timeout page

- apps/industrial-hemp/fields/index.js
- apps/industrial-hemp/index.js
- apps/industrial-hemp/sections/summary-data-sections.js
- apps/industrial-hemp/translations/src/en/fields.json
- apps/industrial-hemp/translations/src/en/pages.json
- apps/industrial-hemp/translations/src/en/validation.json
[CSL-180](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-180) - Are any fields in a different postcode to the site address
[Are any fields in a different postcode to the site address
](https://www.figma.com/design/WNady81HOqgtqgI3L5kAia/CSL---Low-THC-Cannabis?node-id=1-13216&t=YCetZ0bdD17R9I6T-4)
[Provide the addresses of the fields that are in different postcodes](https://www.figma.com/design/WNady81HOqgtqgI3L5kAia/CSL---Low-THC-Cannabis?node-id=1-15436&t=YCetZ0bdD17R9I6T-4)
[What is adjacent to the fields you intend to cultivate?](https://www.figma.com/design/WNady81HOqgtqgI3L5kAia/CSL---Low-THC-Cannabis?node-id=1-15652&t=YCetZ0bdD17R9I6T-4)
- Added necessary page to render fields
- Added validation control and error message
- Added fields
> CSL 180 different postcode

- kube/app/deployment.yml
enabled variables:
`NOTIFY_KEY`
`ADMIN_CLIENT_ID`
`ADMIN_CLIENT_SECRET`
removed redundant variables, which will be imported from configmap-values  (hof-services-config repo)
related PR: https://github.com/UKHomeOfficeForms/hof-services-config/pull/536
`KEYCLOAK_PUBLIC_KEY`
`KEYCLOAK_LOGOUT_URL`
`KEYCLOAK_TOKEN_URL`
> CSL-249: updated env variable list on app deployment file

- apps/registration/fields/index.js
- apps/registration/index.js
- apps/registration/translations/src/en/fields.json
- apps/registration/translations/src/en/pages.json
- apps/registration/translations/src/en/validation.json
- apps/registration/views/content/en/declaration.md
- apps/registration/views/content/en/reg-application-submitted.md
- apps/registration/views/declaration.html
- apps/registration/views/registration-submitted.html
- apps/views/company-type.html
- apps/views/previously-held-licence.html
Relates [CSL-191](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-191)
Includes update changes from [CSL-174](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-174) && figma updates
* adds declaration and confirmation pages
application reference number is todo until iCasework is integrated
> CSL-191 -[REG]- add declaration and confirmation page

- apps/registration/behaviours/submit-request.js
Added `password` variable for Registration password email template;
Removed `referenceNumber` variable for Registration password email template;
Added `username` variable for Registration confirmation email template;
Relates to [CSL-263](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-263)
> CSL-263: password and username variable for email personalisation;

- kube/hof-rds-api/deployment.yml
- kube/html-pdf/html-pdf-deployment.yml
Update hof-rds-api to `3.1.2`
Increase resources available to html-pdf-converter pods
hof-rds-api v3.1.2 includes a new migration changing the applicant_id sequence default. This protects id values up to 20000 which is the potential range that legacy migrated users ids might occupy.
pdf-converter performance slows submission waiting time. Increasing resource requirements will spread the request load further and offer more CPU to processing. These values and management of them can be reassessed later.
> Update hof-rds-api and html-pdf-converter configuration

- .devcontainer/devtools/icasework-mock/icasework-mock.js
- test/unit/pdf-converter.test.js
- utils/pdf-converter.js
Adds a conditional H1 to generated drugs application submission PDFs (applicant and business) where if the value for `application-type` was `amend-application` the title instead has the new format `Amending ${licenceLabel.toLowerCase()} licence application`.
This is to add to work in #188 where a new type is added for amendment type submissions.
Business request as the inclusion of 'Amendment' in the PDF title helps caseworkers to identify amendment type applications.
Unit tests updated to check this new behaviour. 
Tested locally
Updates the returned mock caseid from the local icasework-mock server. The reason for this is that the DB expects an `integer` in the `icasework_case_id` column when adding that column during completion of a submitted drugs application. 
This DB patch will fail …
> CSL-300: Conditional PDF H1 for amendment type applications

- utils/user-creator.js
[CSL-309](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-309) - Add company name attribute to user attributes section
The attribute section for each user has to be updated with company name in keycloak. so have added the attribute in user payload.
companyName from registration is already added in userdetails object.
user payload in userCreator.createRequestConfig is updated with 
`attributes: { 'Company name': companyName }`
> CSL- 309 - Added attribute in user payload to update the attribute in keycloak

- package.json
- yarn.lock
Updated dependency packages to address critical axios vulnerability (https://github.com/advisories/GHSA-rm8p-cx58-hcvx) related to form-data(https://security.snyk.io/vuln/SNYK-JS-FORMDATA-10841150).
updated packages:
```
"form-data": "^4.0.4",
"hof": "^22.8.4",
```
Refers to [CSL-317](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-317)
> CSL-317: Update HOF and relevant dependency packages
